英超:
  曼彻斯特联队: 曼联
  史云斯: 斯旺西
  侯城: 胡尔城
  纽卡斯尔联队: 纽卡斯尔
  史托克城: 斯托克城

西甲:
  格兰纳达: 格拉纳达
  勒万特: 莱万特
  瓦莱卡诺: 巴列卡诺
  格塔菲: 赫塔菲
  瓦拉杜利德: 巴拉多利德
  贝蒂斯: 皇家贝蒂斯
  比利亚雷尔: 比利亚雷亚尔

德甲:
  贺芬咸: 霍芬海姆
  缅恩斯: 美因茨
  弗雷堡: 弗赖堡
  布伦斯维克: 不伦瑞克