# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

league = League.create(:name => '英超')
Team.create(:name => '曼联', :league => league)
Team.create(:name => '斯旺西', :league => league)
Team.create(:name => '胡尔城', :league => league)
Team.create(:name => '纽卡斯尔', :league => league)
Team.create(:name => '斯托克城', :league => league)
Team.create(:name => '卡迪夫城', :league => league)
Team.create(:name => '诺维奇城', :league => league)
Team.create(:name => '南安普顿', :league => league)
Team.create(:name => '阿森纳', :league => league)
Team.create(:name => '富勒姆', :league => league)
Team.create(:name => '水晶宫', :league => league)
Team.create(:name => '利物浦', :league => league)
Team.create(:name => '埃弗顿', :league => league)
Team.create(:name => '阿斯顿维拉', :league => league)
Team.create(:name => '西布朗', :league => league)
Team.create(:name => '切尔西', :league => league)
Team.create(:name => '西汉姆', :league => league)
Team.create(:name => '桑德兰', :league => league)
Team.create(:name => '托特纳姆热刺', :league => league)
Team.create(:name => '曼城', :league => league)

league = League.create(:name => '西甲')
Team.create(:name => '格拉纳达', :league => league)
Team.create(:name => '莱万特', :league => league)
Team.create(:name => '巴列卡诺', :league => league)
Team.create(:name => '赫塔菲', :league => league)
Team.create(:name => '巴拉多利德', :league => league)
Team.create(:name => '皇家贝蒂斯', :league => league)
Team.create(:name => '比利亚雷亚尔', :league => league)
Team.create(:name => '塞尔塔', :league => league)
Team.create(:name => '巴塞罗那', :league => league)
Team.create(:name => '瓦伦西亚', :league => league)
Team.create(:name => '马拉加', :league => league)
Team.create(:name => '塞维利亚', :league => league)
Team.create(:name => '埃尔切', :league => league)
Team.create(:name => '阿尔梅里亚', :league => league)
Team.create(:name => '西班牙人', :league => league)
Team.create(:name => '马德里竞技', :league => league)
Team.create(:name => '皇家社会', :league => league)
Team.create(:name => '毕尔巴鄂', :league => league)
Team.create(:name => '皇家马德里', :league => league)
Team.create(:name => '奥萨苏纳', :league => league)

league = League.create(:name => '德甲')
Team.create(:name => '不伦瑞克', :league => league)
Team.create(:name => '多特蒙德', :league => league)
Team.create(:name => '霍芬海姆', :league => league)
Team.create(:name => '美因茨', :league => league)
Team.create(:name => '弗赖堡', :league => league)
Team.create(:name => '汉堡', :league => league)
Team.create(:name => '勒沃库森', :league => league)
Team.create(:name => '斯图加特', :league => league)
Team.create(:name => '沙尔克04', :league => league)
Team.create(:name => '沃尔夫斯堡', :league => league)
Team.create(:name => '奥格斯堡', :league => league)
Team.create(:name => '云达不莱梅', :league => league)
Team.create(:name => '汉诺威96', :league => league)
Team.create(:name => '门兴格拉德巴赫', :league => league)
Team.create(:name => '柏林赫塔', :league => league)
Team.create(:name => '纽伦堡', :league => league)
Team.create(:name => '拜仁慕尼黑', :league => league)
Team.create(:name => '法兰克福', :league => league)